language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - yarn run build

deploy:
  provider: pages
  fqdn: app.wueww.de
  skip_cleanup: true
  github_token: $github_token
  local_dir: dist
  on:
    branch: master